branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.cache/yarn"
    - "node_modules"
    - "packages/react-dom-model/node_modules"
    - "packages/react-dom-model-selectors/node_modules"
    - "packages/react-dom-model-detox/node_modules"
    - "packages/react-dom-model-tests/node_modules"
    - "packages/test-native-app/node_modules"
    - "packages/test-native-app/ios/build"

before_install:
  - nvm install v8.11.0
  - nvm use
  - npm install
  - npm install -g yarn
  - yarn
  - yarn run bootstrap --concurrency=1

matrix:
  include:
    - stage: test
      language: objective-c
      osx_image: xcode9.3
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - yarn global add detox-cli
      script:
        - yarn test