branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.cache/yarn"

before_install:
  - nvm install v8.11.0
  - nvm use
  - npm install
  - npm install -g yarn
  - yarn
  - yarn run bootstrap --concurrency=1

matrix:
  include:
    - stage: test
      language: objective-c
      osx_image: xcode9.3
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - yarn global add detox-cli
      script:
        - cd packages/react-dom-model-tests && detox build --configuration ios.sim.debug
        - yarn test